from sqlalchemy import cast, String

date_functions = {
            'chart': lambda stock, date: stock.query.filter(stock.date > date).with_entities(
                                                                                                stock.date.cast(String),
                                                                                                stock.open,
                                                                                                stock.adjClose,
                                                                                                stock.volume).all(),
            'general-all': lambda stock, date: stock.query.filter(stock.date > date).with_entities(
                                                                                 stock.date.cast(String),
                                                                                 stock.open,
                                                                                 stock.adjClose,
                                                                                 stock.volume,
                                                                                 stock.high,
                                                                                 stock.low,
                                                                                 stock.count,
                                                                                 stock.value,
                                                                                 stock.close).all(),
            'clients-all': lambda stock, date: stock.query.filter(stock.date > date).with_entities(
                                                                                 stock.date.cast(String),
                                                                                 stock.individual_buy_count,
                                                                                 stock.individual_sell_count,
                                                                                 stock.individual_buy_vol,
                                                                                 stock.individual_sell_vol,
                                                                                 stock.individual_buy_value,
                                                                                 stock.individual_sell_value,
                                                                                 stock.corporate_buy_count,
                                                                                 stock.corporate_sell_count,
                                                                                 stock.corporate_buy_vol,
                                                                                 stock.corporate_sell_vol,
                                                                                 stock.corporate_buy_value,
                                                                                 stock.corporate_sell_value,
                                                                                 stock.individual_buy_mean_price,
                                                                                 stock.individual_sell_mean_price,
                                                                                 stock.corporate_buy_mean_price,
                                                                                 stock.corporate_sell_mean_price,
                                                                                 stock.individual_ownership_change,).all(),
            'all': lambda stock, date: stock.query.filter(stock.date > date).with_entities(
                                                                         stock.date.cast(String),
                                                                         stock.open,
                                                                         stock.adjClose,
                                                                         stock.volume,
                                                                         stock.high,
                                                                         stock.low,
                                                                         stock.count,
                                                                         stock.value,
                                                                         stock.close,
                                                                         stock.individual_buy_count,
                                                                         stock.individual_sell_count,
                                                                         stock.individual_buy_vol,
                                                                         stock.individual_sell_vol,
                                                                         stock.individual_buy_value,
                                                                         stock.individual_sell_value,
                                                                         stock.corporate_buy_count,
                                                                         stock.corporate_sell_count,
                                                                         stock.corporate_buy_vol,
                                                                         stock.corporate_sell_vol,
                                                                         stock.corporate_buy_value,
                                                                         stock.corporate_sell_value,
                                                                         stock.individual_buy_mean_price,
                                                                         stock.individual_sell_mean_price,
                                                                         stock.corporate_buy_mean_price,
                                                                         stock.corporate_sell_mean_price,
                                                                         stock.individual_ownership_change,).all(),
        }