"""empty message

Revision ID: 0eac873d4ae7
Revises: b210b6460c77
Create Date: 2021-05-23 11:12:55.541429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eac873d4ae7'
down_revision = 'b210b6460c77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('نبروج',
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.Column('group', sa.String(length=30), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('adjClose', sa.Float(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('individual_buy_count', sa.Integer(), nullable=True),
    sa.Column('individual_sell_count', sa.Integer(), nullable=True),
    sa.Column('individual_buy_vol', sa.Integer(), nullable=True),
    sa.Column('individual_sell_vol', sa.Integer(), nullable=True),
    sa.Column('individual_buy_value', sa.Integer(), nullable=True),
    sa.Column('individual_sell_value', sa.Integer(), nullable=True),
    sa.Column('corporate_buy_count', sa.Integer(), nullable=True),
    sa.Column('corporate_sell_count', sa.Integer(), nullable=True),
    sa.Column('corporate_buy_vol', sa.Integer(), nullable=True),
    sa.Column('corporate_sell_vol', sa.Integer(), nullable=True),
    sa.Column('corporate_buy_value', sa.Integer(), nullable=True),
    sa.Column('corporate_sell_value', sa.Integer(), nullable=True),
    sa.Column('individual_buy_mean_price', sa.Float(), nullable=True),
    sa.Column('individual_sell_mean_price', sa.Float(), nullable=True),
    sa.Column('corporate_buy_mean_price', sa.Float(), nullable=True),
    sa.Column('corporate_sell_mean_price', sa.Float(), nullable=True),
    sa.Column('individual_ownership_change', sa.Integer(), nullable=True),
    sa.Column('jdate', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('date', name=op.f('pk_نبروج'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('نبروج')
    # ### end Alembic commands ###
