"""empty message

Revision ID: 34492ad15808
Revises: 7c8b00f5c322
Create Date: 2021-05-22 18:07:09.932372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34492ad15808'
down_revision = '7c8b00f5c322'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('شستان',
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.Column('group', sa.String(length=30), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('adjClose', sa.Float(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('individual_buy_count', sa.Integer(), nullable=True),
    sa.Column('individual_sell_count', sa.Integer(), nullable=True),
    sa.Column('individual_buy_vol', sa.Integer(), nullable=True),
    sa.Column('individual_sell_vol', sa.Integer(), nullable=True),
    sa.Column('individual_buy_value', sa.Integer(), nullable=True),
    sa.Column('individual_sell_value', sa.Integer(), nullable=True),
    sa.Column('corporate_buy_count', sa.Integer(), nullable=True),
    sa.Column('corporate_sell_count', sa.Integer(), nullable=True),
    sa.Column('corporate_buy_vol', sa.Integer(), nullable=True),
    sa.Column('corporate_sell_vol', sa.Integer(), nullable=True),
    sa.Column('corporate_buy_value', sa.Integer(), nullable=True),
    sa.Column('corporate_sell_value', sa.Integer(), nullable=True),
    sa.Column('individual_buy_mean_price', sa.Float(), nullable=True),
    sa.Column('individual_sell_mean_price', sa.Float(), nullable=True),
    sa.Column('corporate_buy_mean_price', sa.Float(), nullable=True),
    sa.Column('corporate_sell_mean_price', sa.Float(), nullable=True),
    sa.Column('individual_ownership_change', sa.Integer(), nullable=True),
    sa.Column('jdate', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('date', name=op.f('pk_شستان'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('شستان')
    # ### end Alembic commands ###
