"""empty message

Revision ID: 585a6d9ca2c8
Revises: bd4ae3244ffa
Create Date: 2021-06-08 19:06:51.780312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '585a6d9ca2c8'
down_revision = 'bd4ae3244ffa'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('کتوکاح',
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.Column('group', sa.String(length=30), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('adjClose', sa.Float(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('individual_buy_count', sa.Integer(), nullable=True),
    sa.Column('individual_sell_count', sa.Integer(), nullable=True),
    sa.Column('individual_buy_vol', sa.Integer(), nullable=True),
    sa.Column('individual_sell_vol', sa.Integer(), nullable=True),
    sa.Column('individual_buy_value', sa.Integer(), nullable=True),
    sa.Column('individual_sell_value', sa.Integer(), nullable=True),
    sa.Column('corporate_buy_count', sa.Integer(), nullable=True),
    sa.Column('corporate_sell_count', sa.Integer(), nullable=True),
    sa.Column('corporate_buy_vol', sa.Integer(), nullable=True),
    sa.Column('corporate_sell_vol', sa.Integer(), nullable=True),
    sa.Column('corporate_buy_value', sa.Integer(), nullable=True),
    sa.Column('corporate_sell_value', sa.Integer(), nullable=True),
    sa.Column('individual_buy_mean_price', sa.Float(), nullable=True),
    sa.Column('individual_sell_mean_price', sa.Float(), nullable=True),
    sa.Column('corporate_buy_mean_price', sa.Float(), nullable=True),
    sa.Column('corporate_sell_mean_price', sa.Float(), nullable=True),
    sa.Column('individual_ownership_change', sa.Integer(), nullable=True),
    sa.Column('jdate', sa.String(), nullable=True),
    sa.Column('latin_name', sa.String(), nullable=True),
    sa.Column('individual_buy_power', sa.Float(), nullable=True),
    sa.Column('individual_sell_power', sa.Float(), nullable=True),
    sa.Column('individual_buy_sell_ratio', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('date', name=op.f('pk_کتوکاح'))
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('کتوکاح')
    # ### end Alembic commands ###


def upgrade_stocks_dict():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_stocks_dict():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_today_chart():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('امروزکتوکاح',
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('adjClose', sa.Float(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('individual_buy_count', sa.Integer(), nullable=True),
    sa.Column('individual_sell_count', sa.Integer(), nullable=True),
    sa.Column('individual_buy_vol', sa.Integer(), nullable=True),
    sa.Column('individual_sell_vol', sa.Integer(), nullable=True),
    sa.Column('individual_buy_value', sa.Integer(), nullable=True),
    sa.Column('individual_sell_value', sa.Integer(), nullable=True),
    sa.Column('corporate_buy_count', sa.Integer(), nullable=True),
    sa.Column('corporate_sell_count', sa.Integer(), nullable=True),
    sa.Column('corporate_buy_vol', sa.Integer(), nullable=True),
    sa.Column('corporate_sell_vol', sa.Integer(), nullable=True),
    sa.Column('corporate_buy_value', sa.Integer(), nullable=True),
    sa.Column('corporate_sell_value', sa.Integer(), nullable=True),
    sa.Column('individual_buy_mean_price', sa.Float(), nullable=True),
    sa.Column('individual_sell_mean_price', sa.Float(), nullable=True),
    sa.Column('corporate_buy_mean_price', sa.Float(), nullable=True),
    sa.Column('corporate_sell_mean_price', sa.Float(), nullable=True),
    sa.Column('individual_ownership_change', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('latest_data_time', sa.String(), nullable=True),
    sa.Column('best_demand_count_1', sa.Integer(), nullable=True),
    sa.Column('best_demand_vol_1', sa.Integer(), nullable=True),
    sa.Column('best_demand_val_1', sa.Integer(), nullable=True),
    sa.Column('best_demand_count_2', sa.Integer(), nullable=True),
    sa.Column('best_demand_vol_2', sa.Integer(), nullable=True),
    sa.Column('best_demand_val_2', sa.Integer(), nullable=True),
    sa.Column('best_demand_count_3', sa.Integer(), nullable=True),
    sa.Column('best_demand_vol_3', sa.Integer(), nullable=True),
    sa.Column('best_demand_val_3', sa.Integer(), nullable=True),
    sa.Column('best_demand_count_4', sa.Integer(), nullable=True),
    sa.Column('best_demand_vol_4', sa.Integer(), nullable=True),
    sa.Column('best_demand_val_4', sa.Integer(), nullable=True),
    sa.Column('best_demand_count_5', sa.Integer(), nullable=True),
    sa.Column('best_demand_vol_5', sa.Integer(), nullable=True),
    sa.Column('best_demand_val_5', sa.Integer(), nullable=True),
    sa.Column('best_supply_count_1', sa.Integer(), nullable=True),
    sa.Column('best_supply_vol_1', sa.Integer(), nullable=True),
    sa.Column('best_supply_val_1', sa.Integer(), nullable=True),
    sa.Column('best_supply_count_2', sa.Integer(), nullable=True),
    sa.Column('best_supply_vol_2', sa.Integer(), nullable=True),
    sa.Column('best_supply_val_2', sa.Integer(), nullable=True),
    sa.Column('best_supply_count_3', sa.Integer(), nullable=True),
    sa.Column('best_supply_vol_3', sa.Integer(), nullable=True),
    sa.Column('best_supply_val_3', sa.Integer(), nullable=True),
    sa.Column('best_supply_count_4', sa.Integer(), nullable=True),
    sa.Column('best_supply_vol_4', sa.Integer(), nullable=True),
    sa.Column('best_supply_val_4', sa.Integer(), nullable=True),
    sa.Column('best_supply_count_5', sa.Integer(), nullable=True),
    sa.Column('best_supply_vol_5', sa.Integer(), nullable=True),
    sa.Column('best_supply_val_5', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('time', name=op.f('pk_امروزکتوکاح'))
    )
    # ### end Alembic commands ###


def downgrade_today_chart():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('امروزکتوکاح')
    # ### end Alembic commands ###

