"""empty message

Revision ID: 82f496fdbae3
Revises: 0eac873d4ae7
Create Date: 2021-06-01 21:13:52.509357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82f496fdbae3'
down_revision = '0eac873d4ae7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('غکورش',
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.Column('group', sa.String(length=30), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('adjClose', sa.Float(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('individual_buy_count', sa.Integer(), nullable=True),
    sa.Column('individual_sell_count', sa.Integer(), nullable=True),
    sa.Column('individual_buy_vol', sa.Integer(), nullable=True),
    sa.Column('individual_sell_vol', sa.Integer(), nullable=True),
    sa.Column('individual_buy_value', sa.Integer(), nullable=True),
    sa.Column('individual_sell_value', sa.Integer(), nullable=True),
    sa.Column('corporate_buy_count', sa.Integer(), nullable=True),
    sa.Column('corporate_sell_count', sa.Integer(), nullable=True),
    sa.Column('corporate_buy_vol', sa.Integer(), nullable=True),
    sa.Column('corporate_sell_vol', sa.Integer(), nullable=True),
    sa.Column('corporate_buy_value', sa.Integer(), nullable=True),
    sa.Column('corporate_sell_value', sa.Integer(), nullable=True),
    sa.Column('individual_buy_mean_price', sa.Float(), nullable=True),
    sa.Column('individual_sell_mean_price', sa.Float(), nullable=True),
    sa.Column('corporate_buy_mean_price', sa.Float(), nullable=True),
    sa.Column('corporate_sell_mean_price', sa.Float(), nullable=True),
    sa.Column('individual_ownership_change', sa.Integer(), nullable=True),
    sa.Column('jdate', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('date', name=op.f('pk_غکورش'))
    )
    op.create_table('وامیدح',
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.Column('group', sa.String(length=30), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('adjClose', sa.Float(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('individual_buy_count', sa.Integer(), nullable=True),
    sa.Column('individual_sell_count', sa.Integer(), nullable=True),
    sa.Column('individual_buy_vol', sa.Integer(), nullable=True),
    sa.Column('individual_sell_vol', sa.Integer(), nullable=True),
    sa.Column('individual_buy_value', sa.Integer(), nullable=True),
    sa.Column('individual_sell_value', sa.Integer(), nullable=True),
    sa.Column('corporate_buy_count', sa.Integer(), nullable=True),
    sa.Column('corporate_sell_count', sa.Integer(), nullable=True),
    sa.Column('corporate_buy_vol', sa.Integer(), nullable=True),
    sa.Column('corporate_sell_vol', sa.Integer(), nullable=True),
    sa.Column('corporate_buy_value', sa.Integer(), nullable=True),
    sa.Column('corporate_sell_value', sa.Integer(), nullable=True),
    sa.Column('individual_buy_mean_price', sa.Float(), nullable=True),
    sa.Column('individual_sell_mean_price', sa.Float(), nullable=True),
    sa.Column('corporate_buy_mean_price', sa.Float(), nullable=True),
    sa.Column('corporate_sell_mean_price', sa.Float(), nullable=True),
    sa.Column('individual_ownership_change', sa.Integer(), nullable=True),
    sa.Column('jdate', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('date', name=op.f('pk_وامیدح'))
    )
    op.drop_table('generic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generic',
    sa.Column('name', sa.VARCHAR(length=15), nullable=True),
    sa.Column('group', sa.VARCHAR(length=30), nullable=True),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('open', sa.FLOAT(), nullable=True),
    sa.Column('high', sa.FLOAT(), nullable=True),
    sa.Column('low', sa.FLOAT(), nullable=True),
    sa.Column('adjClose', sa.FLOAT(), nullable=True),
    sa.Column('value', sa.INTEGER(), nullable=True),
    sa.Column('volume', sa.INTEGER(), nullable=True),
    sa.Column('count', sa.INTEGER(), nullable=True),
    sa.Column('close', sa.FLOAT(), nullable=True),
    sa.Column('individual_buy_count', sa.INTEGER(), nullable=True),
    sa.Column('individual_sell_count', sa.INTEGER(), nullable=True),
    sa.Column('individual_buy_vol', sa.INTEGER(), nullable=True),
    sa.Column('individual_sell_vol', sa.INTEGER(), nullable=True),
    sa.Column('individual_buy_value', sa.INTEGER(), nullable=True),
    sa.Column('individual_sell_value', sa.INTEGER(), nullable=True),
    sa.Column('corporate_buy_count', sa.INTEGER(), nullable=True),
    sa.Column('corporate_sell_count', sa.INTEGER(), nullable=True),
    sa.Column('corporate_buy_vol', sa.INTEGER(), nullable=True),
    sa.Column('corporate_sell_vol', sa.INTEGER(), nullable=True),
    sa.Column('corporate_buy_value', sa.INTEGER(), nullable=True),
    sa.Column('corporate_sell_value', sa.INTEGER(), nullable=True),
    sa.Column('individual_buy_mean_price', sa.FLOAT(), nullable=True),
    sa.Column('individual_sell_mean_price', sa.FLOAT(), nullable=True),
    sa.Column('corporate_buy_mean_price', sa.FLOAT(), nullable=True),
    sa.Column('corporate_sell_mean_price', sa.FLOAT(), nullable=True),
    sa.Column('individual_ownership_change', sa.INTEGER(), nullable=True),
    sa.Column('jdate', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('date', name='pk_generic')
    )
    op.drop_table('وامیدح')
    op.drop_table('غکورش')
    # ### end Alembic commands ###
