"""empty message

Revision ID: d5ca4a88a93b
Revises: f5bf1a3b9083
Create Date: 2021-06-04 21:11:29.462704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5ca4a88a93b'
down_revision = 'f5bf1a3b9083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('دی دو')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('دی دو',
    sa.Column('name', sa.VARCHAR(length=15), nullable=True),
    sa.Column('group', sa.VARCHAR(length=30), nullable=True),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('open', sa.FLOAT(), nullable=True),
    sa.Column('high', sa.FLOAT(), nullable=True),
    sa.Column('low', sa.FLOAT(), nullable=True),
    sa.Column('adjClose', sa.FLOAT(), nullable=True),
    sa.Column('value', sa.INTEGER(), nullable=True),
    sa.Column('volume', sa.INTEGER(), nullable=True),
    sa.Column('count', sa.INTEGER(), nullable=True),
    sa.Column('close', sa.FLOAT(), nullable=True),
    sa.Column('individual_buy_count', sa.INTEGER(), nullable=True),
    sa.Column('individual_sell_count', sa.INTEGER(), nullable=True),
    sa.Column('individual_buy_vol', sa.INTEGER(), nullable=True),
    sa.Column('individual_sell_vol', sa.INTEGER(), nullable=True),
    sa.Column('individual_buy_value', sa.INTEGER(), nullable=True),
    sa.Column('individual_sell_value', sa.INTEGER(), nullable=True),
    sa.Column('corporate_buy_count', sa.INTEGER(), nullable=True),
    sa.Column('corporate_sell_count', sa.INTEGER(), nullable=True),
    sa.Column('corporate_buy_vol', sa.INTEGER(), nullable=True),
    sa.Column('corporate_sell_vol', sa.INTEGER(), nullable=True),
    sa.Column('corporate_buy_value', sa.INTEGER(), nullable=True),
    sa.Column('corporate_sell_value', sa.INTEGER(), nullable=True),
    sa.Column('individual_buy_mean_price', sa.FLOAT(), nullable=True),
    sa.Column('individual_sell_mean_price', sa.FLOAT(), nullable=True),
    sa.Column('corporate_buy_mean_price', sa.FLOAT(), nullable=True),
    sa.Column('corporate_sell_mean_price', sa.FLOAT(), nullable=True),
    sa.Column('individual_ownership_change', sa.INTEGER(), nullable=True),
    sa.Column('jdate', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###
