from app.db import StocksBase
from sqlalchemy import Column, Integer, String, Float, DateTime

class Stocks(StocksBase):
    __tablename__ = 'stocks_page'

    id = Column(Integer, primary_key=True)
    name = Column(String(15))
    group = Column(String(30))
    url = Column(String)
    open = Column(Float)
    high = Column(Float)
    low = Column(Float)
    adjClose = Column(Float)
    value = Column(Integer)
    volume = Column(Integer)
    count = Column(Integer)
    close = Column(Float)
    individual_buy_count = Column(Integer)
    individual_sell_count = Column(Integer)
    individual_buy_vol = Column(Integer)
    individual_sell_vol = Column(Integer)
    individual_buy_value = Column(Integer)
    individual_sell_value = Column(Integer)
    corporate_buy_count = Column(Integer)
    corporate_sell_count = Column(Integer)
    corporate_buy_vol = Column(Integer)
    corporate_sell_vol = Column(Integer)
    corporate_buy_value = Column(Integer)
    corporate_sell_value = Column(Integer)
    individual_buy_mean_price = Column(Float)
    individual_sell_mean_price = Column(Float)
    corporate_buy_mean_price = Column(Float)
    corporate_sell_mean_price = Column(Float)
    individual_ownership_change = Column(Integer)
    pe = Column(Float)
    gpe = Column(Float)
    eps = Column(Integer)
    floating_shares = Column(Integer)
    base_volume = Column(Integer)
    total_shares = Column(Integer)
    market_cap = Column(Integer)
    status = Column(String)
    latest_data_time = Column(DateTime)
