from app.db import StocksBase
from sqlalchemy import Column, Integer, String, Float, DateTime, Date
from app.utils.stock_queries import date_functions

class کارین(StocksBase):
    __tablename__ = 'کارین'

    name = Column(String(15))
    group = Column(String(30))
    date = Column(Date, primary_key=True)
    open = Column(Float)
    high = Column(Float)
    low = Column(Float)
    adjClose = Column(Float)
    value = Column(Integer)
    volume = Column(Integer)
    count = Column(Integer)
    close = Column(Float)
    individual_buy_count = Column(Integer)
    individual_sell_count = Column(Integer)
    individual_buy_vol = Column(Integer)
    individual_sell_vol = Column(Integer)
    individual_buy_value = Column(Integer)
    individual_sell_value = Column(Integer)
    corporate_buy_count = Column(Integer)
    corporate_sell_count = Column(Integer)
    corporate_buy_vol = Column(Integer)
    corporate_sell_vol = Column(Integer)
    corporate_buy_value = Column(Integer)
    corporate_sell_value = Column(Integer)
    individual_buy_mean_price = Column(Float)
    individual_sell_mean_price = Column(Float)
    corporate_buy_mean_price = Column(Float)
    corporate_sell_mean_price = Column(Float)
    individual_ownership_change = Column(Integer)
    jdate = Column(String)
    latin_name = Column(String)
    individual_buy_power = Column(Float)
    individual_sell_power = Column(Float)
    individual_buy_sell_ratio = Column(Float)

    def save_to_db(self) -> None:
        db.session.add(self)
        db.session.commit()

    def delete_from_db(self) -> None:
        db.session.delete(self)
        db.session.commit()


    __tablename__ = 'جوین'

    name = Column(String(15))
    group = Column(String(30))
    date = Column(Date, primary_key=True)
    open = Column(Float)
    high = Column(Float)
    low = Column(Float)
    adjClose = Column(Float)
    value = Column(Integer)
    volume = Column(Integer)
    count = Column(Integer)
    close = Column(Float)
    individual_buy_count = Column(Integer)
    individual_sell_count = Column(Integer)
    individual_buy_vol = Column(Integer)
    individual_sell_vol = Column(Integer)
    individual_buy_value = Column(Integer)
    individual_sell_value = Column(Integer)
    corporate_buy_count = Column(Integer)
    corporate_sell_count = Column(Integer)
    corporate_buy_vol = Column(Integer)
    corporate_sell_vol = Column(Integer)
    corporate_buy_value = Column(Integer)
    corporate_sell_value = Column(Integer)
    individual_buy_mean_price = Column(Float)
    individual_sell_mean_price = Column(Float)
    corporate_buy_mean_price = Column(Float)
    corporate_sell_mean_price = Column(Float)
    individual_ownership_change = Column(Integer)
    jdate = Column(String)
    latin_name = Column(String)
    individual_buy_power = Column(Float)
    individual_sell_power = Column(Float)
    individual_buy_sell_ratio = Column(Float)

    def save_to_db(self) -> None:
        db.session.add(self)
        db.session.commit()

    def delete_from_db(self) -> None:
        db.session.delete(self)
        db.session.commit()


    __tablename__ = 'پالایش'

    name = Column(String(15))
    group = Column(String(30))
    date = Column(Date, primary_key=True)
    open = Column(Float)
    high = Column(Float)
    low = Column(Float)
    adjClose = Column(Float)
    value = Column(Integer)
    volume = Column(Integer)
    count = Column(Integer)
    close = Column(Float)
    individual_buy_count = Column(Integer)
    individual_sell_count = Column(Integer)
    individual_buy_vol = Column(Integer)
    individual_sell_vol = Column(Integer)
    individual_buy_value = Column(Integer)
    individual_sell_value = Column(Integer)
    corporate_buy_count = Column(Integer)
    corporate_sell_count = Column(Integer)
    corporate_buy_vol = Column(Integer)
    corporate_sell_vol = Column(Integer)
    corporate_buy_value = Column(Integer)
    corporate_sell_value = Column(Integer)
    individual_buy_mean_price = Column(Float)
    individual_sell_mean_price = Column(Float)
    corporate_buy_mean_price = Column(Float)
    corporate_sell_mean_price = Column(Float)
    individual_ownership_change = Column(Integer)
    jdate = Column(String)
    latin_name = Column(String)
    individual_buy_power = Column(Float)
    individual_sell_power = Column(Float)
    individual_buy_sell_ratio = Column(Float)

    def save_to_db(self) -> None:
        db.session.add(self)
        db.session.commit()

    def delete_from_db(self) -> None:
        db.session.delete(self)
        db.session.commit()


    __tablename__ = 'فردا'

    name = Column(String(15))
    group = Column(String(30))
    date = Column(Date, primary_key=True)
    open = Column(Float)
    high = Column(Float)
    low = Column(Float)
    adjClose = Column(Float)
    value = Column(Integer)
    volume = Column(Integer)
    count = Column(Integer)
    close = Column(Float)
    individual_buy_count = Column(Integer)
    individual_sell_count = Column(Integer)
    individual_buy_vol = Column(Integer)
    individual_sell_vol = Column(Integer)
    individual_buy_value = Column(Integer)
    individual_sell_value = Column(Integer)
    corporate_buy_count = Column(Integer)
    corporate_sell_count = Column(Integer)
    corporate_buy_vol = Column(Integer)
    corporate_sell_vol = Column(Integer)
    corporate_buy_value = Column(Integer)
    corporate_sell_value = Column(Integer)
    individual_buy_mean_price = Column(Float)
    individual_sell_mean_price = Column(Float)
    corporate_buy_mean_price = Column(Float)
    corporate_sell_mean_price = Column(Float)
    individual_ownership_change = Column(Integer)
    jdate = Column(String)
    latin_name = Column(String)
    individual_buy_power = Column(Float)
    individual_sell_power = Column(Float)
    individual_buy_sell_ratio = Column(Float)

    def save_to_db(self) -> None:
        db.session.add(self)
        db.session.commit()

    def delete_from_db(self) -> None:
        db.session.delete(self)
        db.session.commit()


    __tablename__ = 'ومعادنح'

    name = Column(String(15))
    group = Column(String(30))
    date = Column(Date, primary_key=True)
    open = Column(Float)
    high = Column(Float)
    low = Column(Float)
    adjClose = Column(Float)
    value = Column(Integer)
    volume = Column(Integer)
    count = Column(Integer)
    close = Column(Float)
    individual_buy_count = Column(Integer)
    individual_sell_count = Column(Integer)
    individual_buy_vol = Column(Integer)
    individual_sell_vol = Column(Integer)
    individual_buy_value = Column(Integer)
    individual_sell_value = Column(Integer)
    corporate_buy_count = Column(Integer)
    corporate_sell_count = Column(Integer)
    corporate_buy_vol = Column(Integer)
    corporate_sell_vol = Column(Integer)
    corporate_buy_value = Column(Integer)
    corporate_sell_value = Column(Integer)
    individual_buy_mean_price = Column(Float)
    individual_sell_mean_price = Column(Float)
    corporate_buy_mean_price = Column(Float)
    corporate_sell_mean_price = Column(Float)
    individual_ownership_change = Column(Integer)
    jdate = Column(String)
    latin_name = Column(String)
    individual_buy_power = Column(Float)
    individual_sell_power = Column(Float)
    individual_buy_sell_ratio = Column(Float)

    def save_to_db(self) -> None:
        db.session.add(self)
        db.session.commit()

    def delete_from_db(self) -> None:
        db.session.delete(self)
        db.session.commit()


    __tablename__ = 'وخارزمح'

    name = Column(String(15))
    group = Column(String(30))
    date = Column(Date, primary_key=True)
    open = Column(Float)
    high = Column(Float)
    low = Column(Float)
    adjClose = Column(Float)
    value = Column(Integer)
    volume = Column(Integer)
    count = Column(Integer)
    close = Column(Float)
    individual_buy_count = Column(Integer)
    individual_sell_count = Column(Integer)
    individual_buy_vol = Column(Integer)
    individual_sell_vol = Column(Integer)
    individual_buy_value = Column(Integer)
    individual_sell_value = Column(Integer)
    corporate_buy_count = Column(Integer)
    corporate_sell_count = Column(Integer)
    corporate_buy_vol = Column(Integer)
    corporate_sell_vol = Column(Integer)
    corporate_buy_value = Column(Integer)
    corporate_sell_value = Column(Integer)
    individual_buy_mean_price = Column(Float)
    individual_sell_mean_price = Column(Float)
    corporate_buy_mean_price = Column(Float)
    corporate_sell_mean_price = Column(Float)
    individual_ownership_change = Column(Integer)
    jdate = Column(String)
    latin_name = Column(String)
    individual_buy_power = Column(Float)
    individual_sell_power = Column(Float)
    individual_buy_sell_ratio = Column(Float)

    def save_to_db(self) -> None:
        db.session.add(self)
        db.session.commit()

    def delete_from_db(self) -> None:
        db.session.delete(self)
        db.session.commit()


    __tablename__ = 'اپال'

    name = Column(String(15))
    group = Column(String(30))
    date = Column(Date, primary_key=True)
    open = Column(Float)
    high = Column(Float)
    low = Column(Float)
    adjClose = Column(Float)
    value = Column(Integer)
    volume = Column(Integer)
    count = Column(Integer)
    close = Column(Float)
    individual_buy_count = Column(Integer)
    individual_sell_count = Column(Integer)
    individual_buy_vol = Column(Integer)
    individual_sell_vol = Column(Integer)
    individual_buy_value = Column(Integer)
    individual_sell_value = Column(Integer)
    corporate_buy_count = Column(Integer)
    corporate_sell_count = Column(Integer)
    corporate_buy_vol = Column(Integer)
    corporate_sell_vol = Column(Integer)
    corporate_buy_value = Column(Integer)
    corporate_sell_value = Column(Integer)
    individual_buy_mean_price = Column(Float)
    individual_sell_mean_price = Column(Float)
    corporate_buy_mean_price = Column(Float)
    corporate_sell_mean_price = Column(Float)
    individual_ownership_change = Column(Integer)
    jdate = Column(String)
    latin_name = Column(String)
    individual_buy_power = Column(Float)
    individual_sell_power = Column(Float)
    individual_buy_sell_ratio = Column(Float)

    def save_to_db(self) -> None:
        db.session.add(self)
        db.session.commit()

    def delete_from_db(self) -> None:
        db.session.delete(self)
        db.session.commit()


    __tablename__ = 'فباهنرح'

    name = Column(String(15))
    group = Column(String(30))
    date = Column(Date, primary_key=True)
    open = Column(Float)
    high = Column(Float)
    low = Column(Float)
    adjClose = Column(Float)
    value = Column(Integer)
    volume = Column(Integer)
    count = Column(Integer)
    close = Column(Float)
    individual_buy_count = Column(Integer)
    individual_sell_count = Column(Integer)
    individual_buy_vol = Column(Integer)
    individual_sell_vol = Column(Integer)
    individual_buy_value = Column(Integer)
    individual_sell_value = Column(Integer)
    corporate_buy_count = Column(Integer)
    corporate_sell_count = Column(Integer)
    corporate_buy_vol = Column(Integer)
    corporate_sell_vol = Column(Integer)
    corporate_buy_value = Column(Integer)
    corporate_sell_value = Column(Integer)
    individual_buy_mean_price = Column(Float)
    individual_sell_mean_price = Column(Float)
    corporate_buy_mean_price = Column(Float)
    corporate_sell_mean_price = Column(Float)
    individual_ownership_change = Column(Integer)
    jdate = Column(String)
    latin_name = Column(String)
    individual_buy_power = Column(Float)
    individual_sell_power = Column(Float)
    individual_buy_sell_ratio = Column(Float)

    def save_to_db(self) -> None:
        db.session.add(self)
        db.session.commit()

    def delete_from_db(self) -> None:
        db.session.delete(self)
        db.session.commit()


    __tablename__ = 'وسهرمز'

    name = Column(String(15))
    group = Column(String(30))
    date = Column(Date, primary_key=True)
    open = Column(Float)
    high = Column(Float)
    low = Column(Float)
    adjClose = Column(Float)
    value = Column(Integer)
    volume = Column(Integer)
    count = Column(Integer)
    close = Column(Float)
    individual_buy_count = Column(Integer)
    individual_sell_count = Column(Integer)
    individual_buy_vol = Column(Integer)
    individual_sell_vol = Column(Integer)
    individual_buy_value = Column(Integer)
    individual_sell_value = Column(Integer)
    corporate_buy_count = Column(Integer)
    corporate_sell_count = Column(Integer)
    corporate_buy_vol = Column(Integer)
    corporate_sell_vol = Column(Integer)
    corporate_buy_value = Column(Integer)
    corporate_sell_value = Column(Integer)
    individual_buy_mean_price = Column(Float)
    individual_sell_mean_price = Column(Float)
    corporate_buy_mean_price = Column(Float)
    corporate_sell_mean_price = Column(Float)
    individual_ownership_change = Column(Integer)
    jdate = Column(String)
    latin_name = Column(String)
    individual_buy_power = Column(Float)
    individual_sell_power = Column(Float)
    individual_buy_sell_ratio = Column(Float)

    def save_to_db(self) -> None:
        db.session.add(self)
        db.session.commit()

    def delete_from_db(self) -> None:
        db.session.delete(self)
        db.session.commit()


    __tablename__ = 'امینح'

    name = Column(String(15))
    group = Column(String(30))
    date = Column(Date, primary_key=True)
    open = Column(Float)
    high = Column(Float)
    low = Column(Float)
    adjClose = Column(Float)
    value = Column(Integer)
    volume = Column(Integer)
    count = Column(Integer)
    close = Column(Float)
    individual_buy_count = Column(Integer)
    individual_sell_count = Column(Integer)
    individual_buy_vol = Column(Integer)
    individual_sell_vol = Column(Integer)
    individual_buy_value = Column(Integer)
    individual_sell_value = Column(Integer)
    corporate_buy_count = Column(Integer)
    corporate_sell_count = Column(Integer)
    corporate_buy_vol = Column(Integer)
    corporate_sell_vol = Column(Integer)
    corporate_buy_value = Column(Integer)
    corporate_sell_value = Column(Integer)
    individual_buy_mean_price = Column(Float)
    individual_sell_mean_price = Column(Float)
    corporate_buy_mean_price = Column(Float)
    corporate_sell_mean_price = Column(Float)
    individual_ownership_change = Column(Integer)
    jdate = Column(String)
    latin_name = Column(String)
    individual_buy_power = Column(Float)
    individual_sell_power = Column(Float)
    individual_buy_sell_ratio = Column(Float)

    def save_to_db(self) -> None:
        db.session.add(self)
        db.session.commit()

    def delete_from_db(self) -> None:
        db.session.delete(self)
        db.session.commit()


    __tablename__ = 'سپیدما'

    name = Column(String(15))
    group = Column(String(30))
    date = Column(Date, primary_key=True)
    open = Column(Float)
    high = Column(Float)
    low = Column(Float)
    adjClose = Column(Float)
    value = Column(Integer)
    volume = Column(Integer)
    count = Column(Integer)
    close = Column(Float)
    individual_buy_count = Column(Integer)
    individual_sell_count = Column(Integer)
    individual_buy_vol = Column(Integer)
    individual_sell_vol = Column(Integer)
    individual_buy_value = Column(Integer)
    individual_sell_value = Column(Integer)
    corporate_buy_count = Column(Integer)
    corporate_sell_count = Column(Integer)
    corporate_buy_vol = Column(Integer)
    corporate_sell_vol = Column(Integer)
    corporate_buy_value = Column(Integer)
    corporate_sell_value = Column(Integer)
    individual_buy_mean_price = Column(Float)
    individual_sell_mean_price = Column(Float)
    corporate_buy_mean_price = Column(Float)
    corporate_sell_mean_price = Column(Float)
    individual_ownership_change = Column(Integer)
    jdate = Column(String)
    latin_name = Column(String)
    individual_buy_power = Column(Float)
    individual_sell_power = Column(Float)
    individual_buy_sell_ratio = Column(Float)

    def save_to_db(self) -> None:
        db.session.add(self)
        db.session.commit()

    def delete_from_db(self) -> None:
        db.session.delete(self)
        db.session.commit()


    __tablename__ = 'تماوندح'

    name = Column(String(15))
    group = Column(String(30))
    date = Column(Date, primary_key=True)
    open = Column(Float)
    high = Column(Float)
    low = Column(Float)
    adjClose = Column(Float)
    value = Column(Integer)
    volume = Column(Integer)
    count = Column(Integer)
    close = Column(Float)
    individual_buy_count = Column(Integer)
    individual_sell_count = Column(Integer)
    individual_buy_vol = Column(Integer)
    individual_sell_vol = Column(Integer)
    individual_buy_value = Column(Integer)
    individual_sell_value = Column(Integer)
    corporate_buy_count = Column(Integer)
    corporate_sell_count = Column(Integer)
    corporate_buy_vol = Column(Integer)
    corporate_sell_vol = Column(Integer)
    corporate_buy_value = Column(Integer)
    corporate_sell_value = Column(Integer)
    individual_buy_mean_price = Column(Float)
    individual_sell_mean_price = Column(Float)
    corporate_buy_mean_price = Column(Float)
    corporate_sell_mean_price = Column(Float)
    individual_ownership_change = Column(Integer)
    jdate = Column(String)
    latin_name = Column(String)
    individual_buy_power = Column(Float)
    individual_sell_power = Column(Float)
    individual_buy_sell_ratio = Column(Float)

    def save_to_db(self) -> None:
        db.session.add(self)
        db.session.commit()

    def delete_from_db(self) -> None:
        db.session.delete(self)
        db.session.commit()


    __tablename__ = 'خاتم'

    name = Column(String(15))
    group = Column(String(30))
    date = Column(Date, primary_key=True)
    open = Column(Float)
    high = Column(Float)
    low = Column(Float)
    adjClose = Column(Float)
    value = Column(Integer)
    volume = Column(Integer)
    count = Column(Integer)
    close = Column(Float)
    individual_buy_count = Column(Integer)
    individual_sell_count = Column(Integer)
    individual_buy_vol = Column(Integer)
    individual_sell_vol = Column(Integer)
    individual_buy_value = Column(Integer)
    individual_sell_value = Column(Integer)
    corporate_buy_count = Column(Integer)
    corporate_sell_count = Column(Integer)
    corporate_buy_vol = Column(Integer)
    corporate_sell_vol = Column(Integer)
    corporate_buy_value = Column(Integer)
    corporate_sell_value = Column(Integer)
    individual_buy_mean_price = Column(Float)
    individual_sell_mean_price = Column(Float)
    corporate_buy_mean_price = Column(Float)
    corporate_sell_mean_price = Column(Float)
    individual_ownership_change = Column(Integer)
    jdate = Column(String)
    latin_name = Column(String)
    individual_buy_power = Column(Float)
    individual_sell_power = Column(Float)
    individual_buy_sell_ratio = Column(Float)

    def save_to_db(self) -> None:
        db.session.add(self)
        db.session.commit()

    def delete_from_db(self) -> None:
        db.session.delete(self)
        db.session.commit()


    __tablename__ = 'فتوسا'

    name = Column(String(15))
    group = Column(String(30))
    date = Column(Date, primary_key=True)
    open = Column(Float)
    high = Column(Float)
    low = Column(Float)
    adjClose = Column(Float)
    value = Column(Integer)
    volume = Column(Integer)
    count = Column(Integer)
    close = Column(Float)
    individual_buy_count = Column(Integer)
    individual_sell_count = Column(Integer)
    individual_buy_vol = Column(Integer)
    individual_sell_vol = Column(Integer)
    individual_buy_value = Column(Integer)
    individual_sell_value = Column(Integer)
    corporate_buy_count = Column(Integer)
    corporate_sell_count = Column(Integer)
    corporate_buy_vol = Column(Integer)
    corporate_sell_vol = Column(Integer)
    corporate_buy_value = Column(Integer)
    corporate_sell_value = Column(Integer)
    individual_buy_mean_price = Column(Float)
    individual_sell_mean_price = Column(Float)
    corporate_buy_mean_price = Column(Float)
    corporate_sell_mean_price = Column(Float)
    individual_ownership_change = Column(Integer)
    jdate = Column(String)
    latin_name = Column(String)
    individual_buy_power = Column(Float)
    individual_sell_power = Column(Float)
    individual_buy_sell_ratio = Column(Float)

    def save_to_db(self) -> None:
        db.session.add(self)
        db.session.commit()

    def delete_from_db(self) -> None:
        db.session.delete(self)
        db.session.commit()


    __tablename__ = 'زگلدشتح'

    name = Column(String(15))
    group = Column(String(30))
    date = Column(Date, primary_key=True)
    open = Column(Float)
    high = Column(Float)
    low = Column(Float)
    adjClose = Column(Float)
    value = Column(Integer)
    volume = Column(Integer)
    count = Column(Integer)
    close = Column(Float)
    individual_buy_count = Column(Integer)
    individual_sell_count = Column(Integer)
    individual_buy_vol = Column(Integer)
    individual_sell_vol = Column(Integer)
    individual_buy_value = Column(Integer)
    individual_sell_value = Column(Integer)
    corporate_buy_count = Column(Integer)
    corporate_sell_count = Column(Integer)
    corporate_buy_vol = Column(Integer)
    corporate_sell_vol = Column(Integer)
    corporate_buy_value = Column(Integer)
    corporate_sell_value = Column(Integer)
    individual_buy_mean_price = Column(Float)
    individual_sell_mean_price = Column(Float)
    corporate_buy_mean_price = Column(Float)
    corporate_sell_mean_price = Column(Float)
    individual_ownership_change = Column(Integer)
    jdate = Column(String)
    latin_name = Column(String)
    individual_buy_power = Column(Float)
    individual_sell_power = Column(Float)
    individual_buy_sell_ratio = Column(Float)

    def save_to_db(self) -> None:
        db.session.add(self)
        db.session.commit()

    def delete_from_db(self) -> None:
        db.session.delete(self)
        db.session.commit()


    __tablename__ = 'فگستر'

    name = Column(String(15))
    group = Column(String(30))
    date = Column(Date, primary_key=True)
    open = Column(Float)
    high = Column(Float)
    low = Column(Float)
    adjClose = Column(Float)
    value = Column(Integer)
    volume = Column(Integer)
    count = Column(Integer)
    close = Column(Float)
    individual_buy_count = Column(Integer)
    individual_sell_count = Column(Integer)
    individual_buy_vol = Column(Integer)
    individual_sell_vol = Column(Integer)
    individual_buy_value = Column(Integer)
    individual_sell_value = Column(Integer)
    corporate_buy_count = Column(Integer)
    corporate_sell_count = Column(Integer)
    corporate_buy_vol = Column(Integer)
    corporate_sell_vol = Column(Integer)
    corporate_buy_value = Column(Integer)
    corporate_sell_value = Column(Integer)
    individual_buy_mean_price = Column(Float)
    individual_sell_mean_price = Column(Float)
    corporate_buy_mean_price = Column(Float)
    corporate_sell_mean_price = Column(Float)
    individual_ownership_change = Column(Integer)
    jdate = Column(String)
    latin_name = Column(String)
    individual_buy_power = Column(Float)
    individual_sell_power = Column(Float)
    individual_buy_sell_ratio = Column(Float)

    def save_to_db(self) -> None:
        db.session.add(self)
        db.session.commit()

    def delete_from_db(self) -> None:
        db.session.delete(self)
        db.session.commit()


    __tablename__ = 'سپر'

    name = Column(String(15))
    group = Column(String(30))
    date = Column(Date, primary_key=True)
    open = Column(Float)
    high = Column(Float)
    low = Column(Float)
    adjClose = Column(Float)
    value = Column(Integer)
    volume = Column(Integer)
    count = Column(Integer)
    close = Column(Float)
    individual_buy_count = Column(Integer)
    individual_sell_count = Column(Integer)
    individual_buy_vol = Column(Integer)
    individual_sell_vol = Column(Integer)
    individual_buy_value = Column(Integer)
    individual_sell_value = Column(Integer)
    corporate_buy_count = Column(Integer)
    corporate_sell_count = Column(Integer)
    corporate_buy_vol = Column(Integer)
    corporate_sell_vol = Column(Integer)
    corporate_buy_value = Column(Integer)
    corporate_sell_value = Column(Integer)
    individual_buy_mean_price = Column(Float)
    individual_sell_mean_price = Column(Float)
    corporate_buy_mean_price = Column(Float)
    corporate_sell_mean_price = Column(Float)
    individual_ownership_change = Column(Integer)
    jdate = Column(String)
    latin_name = Column(String)
    individual_buy_power = Column(Float)
    individual_sell_power = Column(Float)
    individual_buy_sell_ratio = Column(Float)

    def save_to_db(self) -> None:
        db.session.add(self)
        db.session.commit()

    def delete_from_db(self) -> None:
        db.session.delete(self)
        db.session.commit()


    __tablename__ = 'وبازار'

    name = Column(String(15))
    group = Column(String(30))
    date = Column(Date, primary_key=True)
    open = Column(Float)
    high = Column(Float)
    low = Column(Float)
    adjClose = Column(Float)
    value = Column(Integer)
    volume = Column(Integer)
    count = Column(Integer)
    close = Column(Float)
    individual_buy_count = Column(Integer)
    individual_sell_count = Column(Integer)
    individual_buy_vol = Column(Integer)
    individual_sell_vol = Column(Integer)
    individual_buy_value = Column(Integer)
    individual_sell_value = Column(Integer)
    corporate_buy_count = Column(Integer)
    corporate_sell_count = Column(Integer)
    corporate_buy_vol = Column(Integer)
    corporate_sell_vol = Column(Integer)
    corporate_buy_value = Column(Integer)
    corporate_sell_value = Column(Integer)
    individual_buy_mean_price = Column(Float)
    individual_sell_mean_price = Column(Float)
    corporate_buy_mean_price = Column(Float)
    corporate_sell_mean_price = Column(Float)
    individual_ownership_change = Column(Integer)
    jdate = Column(String)
    latin_name = Column(String)
    individual_buy_power = Column(Float)
    individual_sell_power = Column(Float)
    individual_buy_sell_ratio = Column(Float)

    def save_to_db(self) -> None:
        db.session.add(self)
        db.session.commit()

    def delete_from_db(self) -> None:
        db.session.delete(self)
        db.session.commit()


    __tablename__ = 'باران'

    name = Column(String(15))
    group = Column(String(30))
    date = Column(Date, primary_key=True)
    open = Column(Float)
    high = Column(Float)
    low = Column(Float)
    adjClose = Column(Float)
    value = Column(Integer)
    volume = Column(Integer)
    count = Column(Integer)
    close = Column(Float)
    individual_buy_count = Column(Integer)
    individual_sell_count = Column(Integer)
    individual_buy_vol = Column(Integer)
    individual_sell_vol = Column(Integer)
    individual_buy_value = Column(Integer)
    individual_sell_value = Column(Integer)
    corporate_buy_count = Column(Integer)
    corporate_sell_count = Column(Integer)
    corporate_buy_vol = Column(Integer)
    corporate_sell_vol = Column(Integer)
    corporate_buy_value = Column(Integer)
    corporate_sell_value = Column(Integer)
    individual_buy_mean_price = Column(Float)
    individual_sell_mean_price = Column(Float)
    corporate_buy_mean_price = Column(Float)
    corporate_sell_mean_price = Column(Float)
    individual_ownership_change = Column(Integer)
    jdate = Column(String)
    latin_name = Column(String)
    individual_buy_power = Column(Float)
    individual_sell_power = Column(Float)
    individual_buy_sell_ratio = Column(Float)

    def save_to_db(self) -> None:
        db.session.add(self)
        db.session.commit()

    def delete_from_db(self) -> None:
        db.session.delete(self)
        db.session.commit()


    __tablename__ = 'زرین'

    name = Column(String(15))
    group = Column(String(30))
    date = Column(Date, primary_key=True)
    open = Column(Float)
    high = Column(Float)
    low = Column(Float)
    adjClose = Column(Float)
    value = Column(Integer)
    volume = Column(Integer)
    count = Column(Integer)
    close = Column(Float)
    individual_buy_count = Column(Integer)
    individual_sell_count = Column(Integer)
    individual_buy_vol = Column(Integer)
    individual_sell_vol = Column(Integer)
    individual_buy_value = Column(Integer)
    individual_sell_value = Column(Integer)
    corporate_buy_count = Column(Integer)
    corporate_sell_count = Column(Integer)
    corporate_buy_vol = Column(Integer)
    corporate_sell_vol = Column(Integer)
    corporate_buy_value = Column(Integer)
    corporate_sell_value = Column(Integer)
    individual_buy_mean_price = Column(Float)
    individual_sell_mean_price = Column(Float)
    corporate_buy_mean_price = Column(Float)
    corporate_sell_mean_price = Column(Float)
    individual_ownership_change = Column(Integer)
    jdate = Column(String)
    latin_name = Column(String)
    individual_buy_power = Column(Float)
    individual_sell_power = Column(Float)
    individual_buy_sell_ratio = Column(Float)

    def save_to_db(self) -> None:
        db.session.add(self)
        db.session.commit()

    def delete_from_db(self) -> None:
        db.session.delete(self)
        db.session.commit()


    __tablename__ = 'خبازرس'

    name = Column(String(15))
    group = Column(String(30))
    date = Column(Date, primary_key=True)
    open = Column(Float)
    high = Column(Float)
    low = Column(Float)
    adjClose = Column(Float)
    value = Column(Integer)
    volume = Column(Integer)
    count = Column(Integer)
    close = Column(Float)
    individual_buy_count = Column(Integer)
    individual_sell_count = Column(Integer)
    individual_buy_vol = Column(Integer)
    individual_sell_vol = Column(Integer)
    individual_buy_value = Column(Integer)
    individual_sell_value = Column(Integer)
    corporate_buy_count = Column(Integer)
    corporate_sell_count = Column(Integer)
    corporate_buy_vol = Column(Integer)
    corporate_sell_vol = Column(Integer)
    corporate_buy_value = Column(Integer)
    corporate_sell_value = Column(Integer)
    individual_buy_mean_price = Column(Float)
    individual_sell_mean_price = Column(Float)
    corporate_buy_mean_price = Column(Float)
    corporate_sell_mean_price = Column(Float)
    individual_ownership_change = Column(Integer)
    jdate = Column(String)
    latin_name = Column(String)
    individual_buy_power = Column(Float)
    individual_sell_power = Column(Float)
    individual_buy_sell_ratio = Column(Float)

    def save_to_db(self) -> None:
        db.session.add(self)
        db.session.commit()

    def delete_from_db(self) -> None:
        db.session.delete(self)
        db.session.commit()


    __tablename__ = 'فراز'

    name = Column(String(15))
    group = Column(String(30))
    date = Column(Date, primary_key=True)
    open = Column(Float)
    high = Column(Float)
    low = Column(Float)
    adjClose = Column(Float)
    value = Column(Integer)
    volume = Column(Integer)
    count = Column(Integer)
    close = Column(Float)
    individual_buy_count = Column(Integer)
    individual_sell_count = Column(Integer)
    individual_buy_vol = Column(Integer)
    individual_sell_vol = Column(Integer)
    individual_buy_value = Column(Integer)
    individual_sell_value = Column(Integer)
    corporate_buy_count = Column(Integer)
    corporate_sell_count = Column(Integer)
    corporate_buy_vol = Column(Integer)
    corporate_sell_vol = Column(Integer)
    corporate_buy_value = Column(Integer)
    corporate_sell_value = Column(Integer)
    individual_buy_mean_price = Column(Float)
    individual_sell_mean_price = Column(Float)
    corporate_buy_mean_price = Column(Float)
    corporate_sell_mean_price = Column(Float)
    individual_ownership_change = Column(Integer)
    jdate = Column(String)
    latin_name = Column(String)
    individual_buy_power = Column(Float)
    individual_sell_power = Column(Float)
    individual_buy_sell_ratio = Column(Float)

    def save_to_db(self) -> None:
        db.session.add(self)
        db.session.commit()

    def delete_from_db(self) -> None:
        db.session.delete(self)
        db.session.commit()


    __tablename__ = 'دتوزیعح'

    name = Column(String(15))
    group = Column(String(30))
    date = Column(Date, primary_key=True)
    open = Column(Float)
    high = Column(Float)
    low = Column(Float)
    adjClose = Column(Float)
    value = Column(Integer)
    volume = Column(Integer)
    count = Column(Integer)
    close = Column(Float)
    individual_buy_count = Column(Integer)
    individual_sell_count = Column(Integer)
    individual_buy_vol = Column(Integer)
    individual_sell_vol = Column(Integer)
    individual_buy_value = Column(Integer)
    individual_sell_value = Column(Integer)
    corporate_buy_count = Column(Integer)
    corporate_sell_count = Column(Integer)
    corporate_buy_vol = Column(Integer)
    corporate_sell_vol = Column(Integer)
    corporate_buy_value = Column(Integer)
    corporate_sell_value = Column(Integer)
    individual_buy_mean_price = Column(Float)
    individual_sell_mean_price = Column(Float)
    corporate_buy_mean_price = Column(Float)
    corporate_sell_mean_price = Column(Float)
    individual_ownership_change = Column(Integer)
    jdate = Column(String)
    latin_name = Column(String)
    individual_buy_power = Column(Float)
    individual_sell_power = Column(Float)
    individual_buy_sell_ratio = Column(Float)

    def save_to_db(self) -> None:
        db.session.add(self)
        db.session.commit()

    def delete_from_db(self) -> None:
        db.session.delete(self)
        db.session.commit()


    __tablename__ = 'تمحرکه'

    name = Column(String(15))
    group = Column(String(30))
    date = Column(Date, primary_key=True)
    open = Column(Float)
    high = Column(Float)
    low = Column(Float)
    adjClose = Column(Float)
    value = Column(Integer)
    volume = Column(Integer)
    count = Column(Integer)
    close = Column(Float)
    individual_buy_count = Column(Integer)
    individual_sell_count = Column(Integer)
    individual_buy_vol = Column(Integer)
    individual_sell_vol = Column(Integer)
    individual_buy_value = Column(Integer)
    individual_sell_value = Column(Integer)
    corporate_buy_count = Column(Integer)
    corporate_sell_count = Column(Integer)
    corporate_buy_vol = Column(Integer)
    corporate_sell_vol = Column(Integer)
    corporate_buy_value = Column(Integer)
    corporate_sell_value = Column(Integer)
    individual_buy_mean_price = Column(Float)
    individual_sell_mean_price = Column(Float)
    corporate_buy_mean_price = Column(Float)
    corporate_sell_mean_price = Column(Float)
    individual_ownership_change = Column(Integer)
    jdate = Column(String)
    latin_name = Column(String)
    individual_buy_power = Column(Float)
    individual_sell_power = Column(Float)
    individual_buy_sell_ratio = Column(Float)

    def save_to_db(self) -> None:
        db.session.add(self)
        db.session.commit()

    def delete_from_db(self) -> None:
        db.session.delete(self)
        db.session.commit()


    __tablename__ = 'قیستو'

    name = Column(String(15))
    group = Column(String(30))
    date = Column(Date, primary_key=True)
    open = Column(Float)
    high = Column(Float)
    low = Column(Float)
    adjClose = Column(Float)
    value = Column(Integer)
    volume = Column(Integer)
    count = Column(Integer)
    close = Column(Float)
    individual_buy_count = Column(Integer)
    individual_sell_count = Column(Integer)
    individual_buy_vol = Column(Integer)
    individual_sell_vol = Column(Integer)
    individual_buy_value = Column(Integer)
    individual_sell_value = Column(Integer)
    corporate_buy_count = Column(Integer)
    corporate_sell_count = Column(Integer)
    corporate_buy_vol = Column(Integer)
    corporate_sell_vol = Column(Integer)
    corporate_buy_value = Column(Integer)
    corporate_sell_value = Column(Integer)
    individual_buy_mean_price = Column(Float)
    individual_sell_mean_price = Column(Float)
    corporate_buy_mean_price = Column(Float)
    corporate_sell_mean_price = Column(Float)
    individual_ownership_change = Column(Integer)
    jdate = Column(String)
    latin_name = Column(String)
    individual_buy_power = Column(Float)
    individual_sell_power = Column(Float)
    individual_buy_sell_ratio = Column(Float)

    def save_to_db(self) -> None:
        db.session.add(self)
        db.session.commit()

    def delete_from_db(self) -> None:
        db.session.delete(self)
        db.session.commit()


    __tablename__ = 'شستان'

    name = Column(String(15))
    group = Column(String(30))
    date = Column(Date, primary_key=True)
    open = Column(Float)
    high = Column(Float)
    low = Column(Float)
    adjClose = Column(Float)
    value = Column(Integer)
    volume = Column(Integer)
    count = Column(Integer)
    close = Column(Float)
    individual_buy_count = Column(Integer)
    individual_sell_count = Column(Integer)
    individual_buy_vol = Column(Integer)
    individual_sell_vol = Column(Integer)
    individual_buy_value = Column(Integer)
    individual_sell_value = Column(Integer)
    corporate_buy_count = Column(Integer)
    corporate_sell_count = Column(Integer)
    corporate_buy_vol = Column(Integer)
    corporate_sell_vol = Column(Integer)
    corporate_buy_value = Column(Integer)
    corporate_sell_value = Column(Integer)
    individual_buy_mean_price = Column(Float)
    individual_sell_mean_price = Column(Float)
    corporate_buy_mean_price = Column(Float)
    corporate_sell_mean_price = Column(Float)
    individual_ownership_change = Column(Integer)
    jdate = Column(String)
    latin_name = Column(String)
    individual_buy_power = Column(Float)
    individual_sell_power = Column(Float)
    individual_buy_sell_ratio = Column(Float)

    def save_to_db(self) -> None:
        db.session.add(self)
        db.session.commit()

    def delete_from_db(self) -> None:
        db.session.delete(self)
        db.session.commit()


