from app.db import db
from app.utils.stock_queries import date_functions

class وسپهح(db.Model):
    __tablename__ = 'امروزوسپهح'
    __bind_key__ = 'today_chart'

    time = db.Column(db.DateTime, primary_key=True)
    name = db.Column(db.String(15))
    url = db.Column(db.String)
    open = db.Column(db.Float)
    close = db.Column(db.Float)
    adjClose = db.Column(db.Float)
    count = db.Column(db.Integer)
    value = db.Column(db.Integer)
    volume = db.Column(db.Integer)
    individual_buy_count = db.Column(db.Integer)
    individual_sell_count = db.Column(db.Integer)
    individual_buy_vol = db.Column(db.Integer)
    individual_sell_vol = db.Column(db.Integer)
    individual_buy_value = db.Column(db.Integer)
    individual_sell_value = db.Column(db.Integer)
    corporate_buy_count = db.Column(db.Integer)
    corporate_sell_count = db.Column(db.Integer)
    corporate_buy_vol = db.Column(db.Integer)
    corporate_sell_vol = db.Column(db.Integer)
    corporate_buy_value = db.Column(db.Integer)
    corporate_sell_value = db.Column(db.Integer)
    individual_buy_mean_price = db.Column(db.Float)
    individual_sell_mean_price = db.Column(db.Float)
    corporate_buy_mean_price = db.Column(db.Float)
    corporate_sell_mean_price = db.Column(db.Float)
    individual_ownership_change = db.Column(db.Integer)
    status = db.Column(db.String)
    latest_data_time = db.Column(db.String)
    best_demand_count_1 = db.Column(db.Integer)
    best_demand_vol_1 = db.Column(db.Integer)
    best_demand_val_1 = db.Column(db.Integer)
    best_demand_count_2 = db.Column(db.Integer)
    best_demand_vol_2 = db.Column(db.Integer)
    best_demand_val_2 = db.Column(db.Integer)
    best_demand_count_3 = db.Column(db.Integer)
    best_demand_vol_3 = db.Column(db.Integer)
    best_demand_val_3 = db.Column(db.Integer)
    best_demand_count_4 = db.Column(db.Integer)
    best_demand_vol_4 = db.Column(db.Integer)
    best_demand_val_4 = db.Column(db.Integer)
    best_demand_count_5 = db.Column(db.Integer)
    best_demand_vol_5 = db.Column(db.Integer)
    best_demand_val_5 = db.Column(db.Integer)
    best_supply_count_1 = db.Column(db.Integer)
    best_supply_vol_1 = db.Column(db.Integer)
    best_supply_val_1 = db.Column(db.Integer)
    best_supply_count_2 = db.Column(db.Integer)
    best_supply_vol_2 = db.Column(db.Integer)
    best_supply_val_2 = db.Column(db.Integer)
    best_supply_count_3 = db.Column(db.Integer)
    best_supply_vol_3 = db.Column(db.Integer)
    best_supply_val_3 = db.Column(db.Integer)
    best_supply_count_4 = db.Column(db.Integer)
    best_supply_vol_4 = db.Column(db.Integer)
    best_supply_val_4 = db.Column(db.Integer)
    best_supply_count_5 = db.Column(db.Integer)
    best_supply_vol_5 = db.Column(db.Integer)
    best_supply_val_5 = db.Column(db.Integer)

    @classmethod
    def query_all(cls):
        return cls.query.all()
