from app.db import TodayBase
from sqlalchemy import Column, Integer, String, Float, DateTime
from app.utils.stock_queries import date_functions

class ولقمان(TodayBase):
    __tablename__ = 'امروزولقمان'
    __bind_key__ = 'today_chart'

    time = Column(DateTime, primary_key=True)
    name = Column(String(15))
    url = Column(String)
    open = Column(Float)
    close = Column(Float)
    adjClose = Column(Float)
    count = Column(Integer)
    value = Column(Integer)
    volume = Column(Integer)
    individual_buy_count = Column(Integer)
    individual_sell_count = Column(Integer)
    individual_buy_vol = Column(Integer)
    individual_sell_vol = Column(Integer)
    individual_buy_value = Column(Integer)
    individual_sell_value = Column(Integer)
    corporate_buy_count = Column(Integer)
    corporate_sell_count = Column(Integer)
    corporate_buy_vol = Column(Integer)
    corporate_sell_vol = Column(Integer)
    corporate_buy_value = Column(Integer)
    corporate_sell_value = Column(Integer)
    individual_buy_mean_price = Column(Float)
    individual_sell_mean_price = Column(Float)
    corporate_buy_mean_price = Column(Float)
    corporate_sell_mean_price = Column(Float)
    individual_ownership_change = Column(Integer)
    status = Column(String)
    latest_data_time = Column(String)
    best_demand_count_1 = Column(Integer)
    best_demand_vol_1 = Column(Integer)
    best_demand_val_1 = Column(Integer)
    best_demand_count_2 = Column(Integer)
    best_demand_vol_2 = Column(Integer)
    best_demand_val_2 = Column(Integer)
    best_demand_count_3 = Column(Integer)
    best_demand_vol_3 = Column(Integer)
    best_demand_val_3 = Column(Integer)
    best_demand_count_4 = Column(Integer)
    best_demand_vol_4 = Column(Integer)
    best_demand_val_4 = Column(Integer)
    best_demand_count_5 = Column(Integer)
    best_demand_vol_5 = Column(Integer)
    best_demand_val_5 = Column(Integer)
    best_supply_count_1 = Column(Integer)
    best_supply_vol_1 = Column(Integer)
    best_supply_val_1 = Column(Integer)
    best_supply_count_2 = Column(Integer)
    best_supply_vol_2 = Column(Integer)
    best_supply_val_2 = Column(Integer)
    best_supply_count_3 = Column(Integer)
    best_supply_vol_3 = Column(Integer)
    best_supply_val_3 = Column(Integer)
    best_supply_count_4 = Column(Integer)
    best_supply_vol_4 = Column(Integer)
    best_supply_val_4 = Column(Integer)
    best_supply_count_5 = Column(Integer)
    best_supply_vol_5 = Column(Integer)
    best_supply_val_5 = Column(Integer)

